# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-solution-builder-cloud-sql
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Cloud SQL
    source:
      repo: https://github.com/ayushmjain/terraform-google-solution-builder-cloud-sql.git
      sourceType: git
    version: 0.0.1
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description:
      tagline: Cloud SQL is a fully-managed relational database service in GCP.
      detailed: This composition unit creates a Cloud SQL database of type PostgreSQL which can be accessed using a service account.
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    icon: assets/icon.png
    costEstimate:
      description: Blueprint cost details
      url: https://cloud.google.com/products/calculator?hl=en&dl=CiQxNzNiMzcyYy05YjkwLTQ0MjEtOTMzOS1mY2QzMjE5OWNmMWMQBxokNjczNTk5RjEtOTY3NC00QzQxLTg4RjctRjAzRTA1NUUzQ0E3
  content:
    documentation:
    - title: Cloud SQL
      url: https://cloud.google.com/sql/docs/introduction
    clientLibraryDocumentationLink: https://cloud.google.com/sql/docs/mysql/admin-api/libraries
    codeSampleLink: https://cloud.google.com/sql/docs/mysql/samples
    examples:
    - name: simple_example
      location: examples/simple_example
  interfaces:
    variables:
    - name: database_name
      description: Database name
      varType: string
      required: true
      userInputVariable: true
    - name: network_dependency
      description: Dependency on VPC Network
      varType: any
      defaultValue: null
      userInputVariable: false
      connections:
      - compositionUnitID: terraform-google-solution-builder-vpc-network
        type: direct
        output: module_dependency
    - name: network_name
      description: VPC network name where the Cloud SQL database is created
      varType: string
      defaultValue: null
      userInputVariable: true
      connections:
      - compositionUnitID: terraform-google-solution-builder-vpc-network
        type: direct
        output: network_name
    - name: project_id
      description: GCP project ID where the Cloud SQL database is created
      varType: string
      required: true
      userInputVariable: true
    - name: region
      description: GCP region where the Cloud SQL database is created
      varType: string
      required: true
      userInputVariable: true
    - name: user_service_account_name
      description: Service account name that accesses the database
      varType: string
      required: true
      userInputVariable: true
      connections:
      - compositionUnitID: terraform-google-solution-builder-cloud-run
        type: direct
        output: cloud_run_service_account_name
    - name: disk_size
      description: The size of data disk in GB
      varType: number
      defaultValue: 10
      userInputVariable: true
    - name: database_version
      description: Database version
      varType: string
      defaultValue: POSTGRES_14
      userInputVariable: true
      oneOf:
      - MYSQL_5_6
      - MYSQL_5_7
      - MYSQL_8_0
      - POSTGRES_9_6
      - POSTGRES_10
      - POSTGRES_11
      - POSTGRES_12
      - POSTGRES_13
      - POSTGRES_14
      - POSTGRES_15
      - SQLSERVER_2017_STANDARD
      - SQLSERVER_2017_ENTERPRISE
      - SQLSERVER_2017_EXPRESS
      - SQLSERVER_2017_WEB
      - SQLSERVER_2019_STANDARD
      - SQLSERVER_2019_ENTERPRISE
      - SQLSERVER_2019_EXPRESS
      - SQLSERVER_2019_WEB
    outputs:
    - name: database_connection_name
      description: Cloud SQL database connection name
      solutionOutputVariable: false
    - name: database_host
      description: Cloud SQL database host
      solutionOutputVariable: true
    - name: database_name
      description: Cloud SQL database name
      solutionOutputVariable: false
    - name: module_dependency
      description: Dependency variable that can be used by other modules to depend on this module
      solutionOutputVariable: false
    - name: env_variables
      description: Environment variables exposed by the Cloud SQL module that can be used by compute resources to connect to the Cloud SQL database
      solutionOutputVariable: false
  requirements:
    roles:
    - level: Project
      roles:
      - roles/cloudsql.admin
    services:
    - sql-component.googleapis.com
    - sqladmin.googleapis.com
